### ISSUE TITLE
Unable to build app after upgrading to version 4.5.0.

### ISSUE THREAD

**Issue by kaisontan** [BlinkID/blinkid-react-native#100]
Hi, I was using microblink-react-native plugin since 2018 May. It was working fine in version 4.2.0. Recently I  noticed there are new version(v4.5.0) which included new Recognizers (Eg. malaysiaMyKadBackRecognizer.js, malaysiaMyKadFrontRecognizer.js, bruneiIdFrontRecognizer.js, etc.). However, after upgraded to version 4.5.0, I was unable to build the app. The error seen like missing folders/ files. 

Task :blinkid-react-native:compileDebugJavaWithJavac
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/BruneiIdFrontRecognizerSerialization.java:12: error: package com.microblink.entities.recognizers.blinkid.brunei does not exist
        com.microblink.entities.recognizers.blinkid.brunei.BruneiIdFrontRecognizer recognizer = new com.microblink.entities.recognizers.blinkid.brunei.BruneiIdFrontRecognizer();
                                                          ^
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/BruneiIdFrontRecognizerSerialization.java:12: error: package com.microblink.entities.recognizers.blinkid.brunei does not exist
        com.microblink.entities.recognizers.blinkid.brunei.BruneiIdFrontRecognizer recognizer = new com.microblink.entities.recognizers.blinkid.brunei.BruneiIdFrontRecognizer();
                                                                                                                                                      ^
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/BruneiIdFrontRecognizerSerialization.java:48: error: package com.microblink.entities.recognizers.blinkid.brunei.BruneiIdFrontRecognizer does not exist
        com.microblink.entities.recognizers.blinkid.brunei.BruneiIdFrontRecognizer.Result result = ((com.microblink.entities.recognizers.blinkid.brunei.BruneiIdFrontRecognizer)recognizer).getResult();
                                                                                  ^
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/BruneiIdFrontRecognizerSerialization.java:48: error: package com.microblink.entities.recognizers.blinkid.brunei does not exist
        com.microblink.entities.recognizers.blinkid.brunei.BruneiIdFrontRecognizer.Result result = ((com.microblink.entities.recognizers.blinkid.brunei.BruneiIdFrontRecognizer)recognizer).getResult();
                                                                                                                                                       ^
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/BruneiIdFrontRecognizerSerialization.java:68: error: package com.microblink.entities.recognizers.blinkid.brunei does not exist
        return com.microblink.entities.recognizers.blinkid.brunei.BruneiIdFrontRecognizer.class;
                                                                 ^
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/CyprusIdBackRecognizerSerialization.java:34: error: cannot find symbol
        jsonResult.putMap("mrzResult", BlinkIDSerializationUtils.serializeMrzResult(result.getMrzResult()));
                                                                                          ^
  symbol:   method getMrzResult()
  location: variable result of type Result
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/CyprusIdFrontRecognizerSerialization.java:32: error: cannot find symbol
            recognizer.setReturnSignatureImage(jsonRecognizer.getBoolean("returnSignatureImage"));
                      ^
  symbol:   method setReturnSignatureImage(boolean)
  location: variable recognizer of type CyprusIdFrontRecognizer
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/CyprusIdFrontRecognizerSerialization.java:35: error: cannot find symbol
            recognizer.setSignatureImageDpi(jsonRecognizer.getInt("signatureImageDpi"));
                      ^
  symbol:   method setSignatureImageDpi(int)
  location: variable recognizer of type CyprusIdFrontRecognizer
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/CyprusIdFrontRecognizerSerialization.java:48: error: cannot find symbol
        jsonResult.putString("signatureImage", SerializationUtils.encodeImageBase64(result.getSignatureImage()));
                                                                                          ^
  symbol:   method getSignatureImage()
  location: variable result of type Result
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/CyprusOldIdBackRecognizerSerialization.java:12: error: cannot find symbol
        com.microblink.entities.recognizers.blinkid.cyprus.CyprusOldIdBackRecognizer recognizer = new com.microblink.entities.recognizers.blinkid.cyprus.CyprusOldIdBackRecognizer();
                                                          ^
  symbol:   class CyprusOldIdBackRecognizer
  location: package com.microblink.entities.recognizers.blinkid.cyprus
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/CyprusOldIdBackRecognizerSerialization.java:12: error: cannot find symbol
        com.microblink.entities.recognizers.blinkid.cyprus.CyprusOldIdBackRecognizer recognizer = new com.microblink.entities.recognizers.blinkid.cyprus.CyprusOldIdBackRecognizer();
                                                                                                                                                        ^
  symbol:   class CyprusOldIdBackRecognizer
  location: package com.microblink.entities.recognizers.blinkid.cyprus
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/CyprusOldIdBackRecognizerSerialization.java:36: error: package com.microblink.entities.recognizers.blinkid.cyprus.CyprusOldIdBackRecognizer does not exist
        com.microblink.entities.recognizers.blinkid.cyprus.CyprusOldIdBackRecognizer.Result result = ((com.microblink.entities.recognizers.blinkid.cyprus.CyprusOldIdBackRecognizer)recognizer).getResult();
                                                                                    ^
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/CyprusOldIdBackRecognizerSerialization.java:36: error: cannot find symbol
        com.microblink.entities.recognizers.blinkid.cyprus.CyprusOldIdBackRecognizer.Result result = ((com.microblink.entities.recognizers.blinkid.cyprus.CyprusOldIdBackRecognizer)recognizer).getResult();
                                                                                                                                                         ^
  symbol:   class CyprusOldIdBackRecognizer
  location: package com.microblink.entities.recognizers.blinkid.cyprus
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/CyprusOldIdBackRecognizerSerialization.java:53: error: cannot find symbol
        return com.microblink.entities.recognizers.blinkid.cyprus.CyprusOldIdBackRecognizer.class;
                                                                 ^
  symbol:   class CyprusOldIdBackRecognizer
  location: package com.microblink.entities.recognizers.blinkid.cyprus
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/CyprusOldIdFrontRecognizerSerialization.java:12: error: cannot find symbol
        com.microblink.entities.recognizers.blinkid.cyprus.CyprusOldIdFrontRecognizer recognizer = new com.microblink.entities.recognizers.blinkid.cyprus.CyprusOldIdFrontRecognizer();
                                                          ^
  symbol:   class CyprusOldIdFrontRecognizer
  location: package com.microblink.entities.recognizers.blinkid.cyprus
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/CyprusOldIdFrontRecognizerSerialization.java:12: error: cannot find symbol
        com.microblink.entities.recognizers.blinkid.cyprus.CyprusOldIdFrontRecognizer recognizer = new com.microblink.entities.recognizers.blinkid.cyprus.CyprusOldIdFrontRecognizer();
                                                                                                                                                         ^
  symbol:   class CyprusOldIdFrontRecognizer
  location: package com.microblink.entities.recognizers.blinkid.cyprus
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/CyprusOldIdFrontRecognizerSerialization.java:45: error: package com.microblink.entities.recognizers.blinkid.cyprus.CyprusOldIdFrontRecognizer does not exist
        com.microblink.entities.recognizers.blinkid.cyprus.CyprusOldIdFrontRecognizer.Result result = ((com.microblink.entities.recognizers.blinkid.cyprus.CyprusOldIdFrontRecognizer)recognizer).getResult();
                                                                                     ^
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/CyprusOldIdFrontRecognizerSerialization.java:45: error: cannot find symbol
        com.microblink.entities.recognizers.blinkid.cyprus.CyprusOldIdFrontRecognizer.Result result = ((com.microblink.entities.recognizers.blinkid.cyprus.CyprusOldIdFrontRecognizer)recognizer).getResult();
                                                                                                                                                          ^
  symbol:   class CyprusOldIdFrontRecognizer
  location: package com.microblink.entities.recognizers.blinkid.cyprus
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/CyprusOldIdFrontRecognizerSerialization.java:64: error: cannot find symbol
        return com.microblink.entities.recognizers.blinkid.cyprus.CyprusOldIdFrontRecognizer.class;
                                                                 ^
  symbol:   class CyprusOldIdFrontRecognizer
  location: package com.microblink.entities.recognizers.blinkid.cyprus
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/MalaysiaIkadFrontRecognizerSerialization.java:12: error: cannot find symbol
        com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaIkadFrontRecognizer recognizer = new com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaIkadFrontRecognizer();
                                                            ^
  symbol:   class MalaysiaIkadFrontRecognizer
  location: package com.microblink.entities.recognizers.blinkid.malaysia
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/MalaysiaIkadFrontRecognizerSerialization.java:12: error: cannot find symbol
        com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaIkadFrontRecognizer recognizer = new com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaIkadFrontRecognizer();
                                                                                                                                                              ^
  symbol:   class MalaysiaIkadFrontRecognizer
  location: package com.microblink.entities.recognizers.blinkid.malaysia
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/MalaysiaIkadFrontRecognizerSerialization.java:63: error: package com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaIkadFrontRecognizer does not exist
        com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaIkadFrontRecognizer.Result result = ((com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaIkadFrontRecognizer)recognizer).getResult();
                                                                                        ^
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/MalaysiaIkadFrontRecognizerSerialization.java:63: error: cannot find symbol
        com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaIkadFrontRecognizer.Result result = ((com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaIkadFrontRecognizer)recognizer).getResult();
                                                                                                                                                               ^
  symbol:   class MalaysiaIkadFrontRecognizer
  location: package com.microblink.entities.recognizers.blinkid.malaysia
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/MalaysiaIkadFrontRecognizerSerialization.java:88: error: cannot find symbol
        return com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaIkadFrontRecognizer.class;
                                                                   ^
  symbol:   class MalaysiaIkadFrontRecognizer
  location: package com.microblink.entities.recognizers.blinkid.malaysia
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/MalaysiaMyKadBackRecognizerSerialization.java:12: error: cannot find symbol
        com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyKadBackRecognizer recognizer = new com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyKadBackRecognizer();
                                                            ^
  symbol:   class MalaysiaMyKadBackRecognizer
  location: package com.microblink.entities.recognizers.blinkid.malaysia
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/MalaysiaMyKadBackRecognizerSerialization.java:12: error: cannot find symbol
        com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyKadBackRecognizer recognizer = new com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyKadBackRecognizer();
                                                                                                                                                              ^
  symbol:   class MalaysiaMyKadBackRecognizer
  location: package com.microblink.entities.recognizers.blinkid.malaysia
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/MalaysiaMyKadBackRecognizerSerialization.java:39: error: package com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyKadBackRecognizer does not exist
        com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyKadBackRecognizer.Result result = ((com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyKadBackRecognizer)recognizer).getResult();
                                                                                        ^
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/MalaysiaMyKadBackRecognizerSerialization.java:39: error: cannot find symbol
        com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyKadBackRecognizer.Result result = ((com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyKadBackRecognizer)recognizer).getResult();
                                                                                                                                                               ^
  symbol:   class MalaysiaMyKadBackRecognizer
  location: package com.microblink.entities.recognizers.blinkid.malaysia
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/MalaysiaMyKadBackRecognizerSerialization.java:59: error: cannot find symbol
        return com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyKadBackRecognizer.class;
                                                                   ^
  symbol:   class MalaysiaMyKadBackRecognizer
  location: package com.microblink.entities.recognizers.blinkid.malaysia
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/MalaysiaMyKadFrontRecognizerSerialization.java:12: error: cannot find symbol
        com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyKadFrontRecognizer recognizer = new com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyKadFrontRecognizer();
                                                            ^
  symbol:   class MalaysiaMyKadFrontRecognizer
  location: package com.microblink.entities.recognizers.blinkid.malaysia
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/MalaysiaMyKadFrontRecognizerSerialization.java:12: error: cannot find symbol
        com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyKadFrontRecognizer recognizer = new com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyKadFrontRecognizer();
                                                                                                                                                               ^
  symbol:   class MalaysiaMyKadFrontRecognizer
  location: package com.microblink.entities.recognizers.blinkid.malaysia
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/MalaysiaMyKadFrontRecognizerSerialization.java:45: error: package com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyKadFrontRecognizer does not exist
        com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyKadFrontRecognizer.Result result = ((com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyKadFrontRecognizer)recognizer).getResult();
                                                                                         ^
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/MalaysiaMyKadFrontRecognizerSerialization.java:45: error: cannot find symbol
        com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyKadFrontRecognizer.Result result = ((com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyKadFrontRecognizer)recognizer).getResult();
                                                                                                                                                                ^
  symbol:   class MalaysiaMyKadFrontRecognizer
  location: package com.microblink.entities.recognizers.blinkid.malaysia
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/MalaysiaMyKadFrontRecognizerSerialization.java:70: error: cannot find symbol
        return com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyKadFrontRecognizer.class;
                                                                   ^
  symbol:   class MalaysiaMyKadFrontRecognizer
  location: package com.microblink.entities.recognizers.blinkid.malaysia
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/MalaysiaMyKasFrontRecognizerSerialization.java:12: error: cannot find symbol
        com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyKasFrontRecognizer recognizer = new com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyKasFrontRecognizer();
                                                            ^
  symbol:   class MalaysiaMyKasFrontRecognizer
  location: package com.microblink.entities.recognizers.blinkid.malaysia
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/MalaysiaMyKasFrontRecognizerSerialization.java:12: error: cannot find symbol
        com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyKasFrontRecognizer recognizer = new com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyKasFrontRecognizer();
                                                                                                                                                               ^
  symbol:   class MalaysiaMyKasFrontRecognizer
  location: package com.microblink.entities.recognizers.blinkid.malaysia
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/MalaysiaMyKasFrontRecognizerSerialization.java:45: error: package com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyKasFrontRecognizer does not exist
        com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyKasFrontRecognizer.Result result = ((com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyKasFrontRecognizer)recognizer).getResult();
                                                                                         ^
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/MalaysiaMyKasFrontRecognizerSerialization.java:45: error: cannot find symbol
        com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyKasFrontRecognizer.Result result = ((com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyKasFrontRecognizer)recognizer).getResult();
                                                                                                                                                                ^
  symbol:   class MalaysiaMyKasFrontRecognizer
  location: package com.microblink.entities.recognizers.blinkid.malaysia
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/MalaysiaMyKasFrontRecognizerSerialization.java:71: error: cannot find symbol
        return com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyKasFrontRecognizer.class;
                                                                   ^
  symbol:   class MalaysiaMyKasFrontRecognizer
  location: package com.microblink.entities.recognizers.blinkid.malaysia
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/MalaysiaMyPrFrontRecognizerSerialization.java:12: error: cannot find symbol
        com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyPrFrontRecognizer recognizer = new com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyPrFrontRecognizer();
                                                            ^
  symbol:   class MalaysiaMyPrFrontRecognizer
  location: package com.microblink.entities.recognizers.blinkid.malaysia
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/MalaysiaMyPrFrontRecognizerSerialization.java:12: error: cannot find symbol
        com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyPrFrontRecognizer recognizer = new com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyPrFrontRecognizer();
                                                                                                                                                              ^
  symbol:   class MalaysiaMyPrFrontRecognizer
  location: package com.microblink.entities.recognizers.blinkid.malaysia
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/MalaysiaMyPrFrontRecognizerSerialization.java:45: error: package com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyPrFrontRecognizer does not exist
        com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyPrFrontRecognizer.Result result = ((com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyPrFrontRecognizer)recognizer).getResult();
                                                                                        ^
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/MalaysiaMyPrFrontRecognizerSerialization.java:45: error: cannot find symbol
        com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyPrFrontRecognizer.Result result = ((com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyPrFrontRecognizer)recognizer).getResult();
                                                                                                                                                               ^
  symbol:   class MalaysiaMyPrFrontRecognizer
  location: package com.microblink.entities.recognizers.blinkid.malaysia
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/MalaysiaMyPrFrontRecognizerSerialization.java:71: error: cannot find symbol
        return com.microblink.entities.recognizers.blinkid.malaysia.MalaysiaMyPrFrontRecognizer.class;
                                                                   ^
  symbol:   class MalaysiaMyPrFrontRecognizer
  location: package com.microblink.entities.recognizers.blinkid.malaysia
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/MrtdRecognizerSerialization.java:23: error: cannot find symbol
            recognizer.setFullDocumentImageDpi(jsonRecognizer.getInt("fullDocumentImageDpi"));
                      ^
  symbol:   method setFullDocumentImageDpi(int)
  location: variable recognizer of type MrtdRecognizer
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/MrtdRecognizerSerialization.java:26: error: cannot find symbol
            recognizer.setFullDocumentImageExtensionFactors(BlinkIDSerializationUtils.deserializeExtensionFactors(jsonRecognizer.getMap("fullDocumentImageExtensionFactors")));
                      ^
  symbol:   method setFullDocumentImageExtensionFactors(ImageExtensionFactors)
  location: variable recognizer of type MrtdRecognizer
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/MrtdRecognizerSerialization.java:29: error: cannot find symbol
            recognizer.setMrzImageDpi(jsonRecognizer.getInt("mrzImageDpi"));
                      ^
  symbol:   method setMrzImageDpi(int)
  location: variable recognizer of type MrtdRecognizer
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/SwitzerlandIdBackRecognizerSerialization.java:35: error: cannot find symbol
            recognizer.setFullDocumentImageDpi(jsonRecognizer.getInt("fullDocumentImageDpi"));
                      ^
  symbol:   method setFullDocumentImageDpi(int)
  location: variable recognizer of type SwitzerlandIdBackRecognizer
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/SwitzerlandIdBackRecognizerSerialization.java:38: error: cannot find symbol
            recognizer.setFullDocumentImageExtensionFactors(BlinkIDSerializationUtils.deserializeExtensionFactors(jsonRecognizer.getMap("fullDocumentImageExtensionFactors")));
                      ^
  symbol:   method setFullDocumentImageExtensionFactors(ImageExtensionFactors)
  location: variable recognizer of type SwitzerlandIdBackRecognizer
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/SwitzerlandIdBackRecognizerSerialization.java:56: error: cannot find symbol
        jsonResult.putMap("mrzResult", BlinkIDSerializationUtils.serializeMrzResult(result.getMrzResult()));
                                                                                          ^
  symbol:   method getMrzResult()
  location: variable result of type Result
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/SwitzerlandPassportRecognizerSerialization.java:38: error: cannot find symbol
            recognizer.setExtractPlaceOfOrigin(jsonRecognizer.getBoolean("extractPlaceOfOrigin"));
                      ^
  symbol:   method setExtractPlaceOfOrigin(boolean)
  location: variable recognizer of type SwitzerlandPassportRecognizer
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/SwitzerlandPassportRecognizerSerialization.java:47: error: cannot find symbol
            recognizer.setFaceImageDpi(jsonRecognizer.getInt("faceImageDpi"));
                      ^
  symbol:   method setFaceImageDpi(int)
  location: variable recognizer of type SwitzerlandPassportRecognizer
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/SwitzerlandPassportRecognizerSerialization.java:50: error: cannot find symbol
            recognizer.setFullDocumentImageDpi(jsonRecognizer.getInt("fullDocumentImageDpi"));
                      ^
  symbol:   method setFullDocumentImageDpi(int)
  location: variable recognizer of type SwitzerlandPassportRecognizer
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/SwitzerlandPassportRecognizerSerialization.java:53: error: cannot find symbol
            recognizer.setFullDocumentImageExtensionFactors(BlinkIDSerializationUtils.deserializeExtensionFactors(jsonRecognizer.getMap("fullDocumentImageExtensionFactors")));
                      ^
  symbol:   method setFullDocumentImageExtensionFactors(ImageExtensionFactors)
  location: variable recognizer of type SwitzerlandPassportRecognizer
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/SwitzerlandPassportRecognizerSerialization.java:77: error: cannot find symbol
        jsonResult.putMap("mrzResult", BlinkIDSerializationUtils.serializeMrzResult(result.getMrzResult()));
                                                                                          ^
  symbol:   method getMrzResult()
  location: variable result of type Result
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/recognizers/serialization/SwitzerlandPassportRecognizerSerialization.java:79: error: cannot find symbol
        jsonResult.putString("placeOfOrigin", result.getPlaceOfOrigin());
                                                    ^
  symbol:   method getPlaceOfOrigin()
  location: variable result of type Result
56 errors

**Comment by kaisontan** [comment]
I noticed that although in build.gradle, dependencies have specify to use com.microblink:blinkid:4.5.0@aar, but when I build the app, the gradle pull com.microblink:blinkid:4.4.0@aar instead. Not sure how I did it, suddenly it start pulling the correct version already.

**Comment by i1E** [comment]
Hi @kaisontan, 

we are glad that now everything works fine.
