### ISSUE TITLE
Build step fails on blink-id for android

### ISSUE THREAD

**Issue by jeaniekarina** [BlinkID/blinkid-react-native#117]
Blinkid builds for ios but not for android, this is error I got when running react-native run-android. 

```
error: cannot find symbol
import com.facebook.react.bridge.BaseActivityEventListener;
                                ^
  symbol:   class BaseActivityEventListener
  location: package com.facebook.react.bridge
/Users/jeanieorejarena/Sites/pit-pay/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/MicroblinkModule.java:119: error: cannot find symbol
    private final ActivityEventListener mScanActivityListener = new BaseActivityEventListener() {
                                                                    ^
  symbol:   class BaseActivityEventListener
  location: class MicroblinkModule
```

This is what my build.gradle file looks like after running `react-native link blinkid-react-native` and updating the gradle file:

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
    }


    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        // Add jitpack repository (added by tipsi-stripe)
        google()
        mavenLocal()
        jcenter()
        maven { url "https://jitpack.io" }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
           url "http://maven.microblink.com"
        }
    }
}
```

Can anyone help me figure this out?

**Comment by i1E** [comment]
Hi @jeaniekarina,

which React-Native version you are using?

**Comment by jeaniekarina** [comment]
I am version 0.59.5

**Comment by i1E** [comment]
Hi @jeaniekarina,

does the sample app, which can be created by running [initReactNativeDemoApp.sh](https://github.com/BlinkID/blinkid-react-native/blob/master/initReactNativeDemoApp.sh) work for you?

We have updated to RN version 0.59.5 in initReactNativeDemoApp script, built the application and it worked.

Please try to clean build your project (and clear all caches).

**Comment by jeevankumarkanuganti** [comment]
after migrating the project to android X, i am also getting error.

/android/src/main/java/com/microblink/reactnative/MicroblinkModule.java:6: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.ActivityEventListener;
                                ^
/node_modules/blinkid-react-native/src/android/src/main/java/com/microblink/reactnative/MicroblinkModule.java:7: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.BaseActivityEventListener;

**Comment by i1E** [comment]
Hi @jeevankumarkanuganti,

sorry for the late reply, have you managed to build the project? You can try the latest version of our plugin (v5.3.0) which works with React Native v0.61.5.

Best regards

**Comment by mparadina** [comment]
Hi @jeevankumarkanuganti 

As this issue is inactive we would like to solve it.

If this is still an open issue for you, feel free to re-open this issue or create a new one.

Also, you can always contact us directly at support@microblink.com for further questions.
We will be more than glad to help.

Regards,
Milan
